name: Go CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: setup
      run: make setup
    - name: build
      run: make all
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: bin

  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: setup
      run: make setup
    - name: test
      run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: lint
      uses: golangci/golangci-lint-action@v6
